name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: purcell/setup-emacs@v3.0
        with:
          version: 27.2
      - uses: leotaku/elisp-check@v1.1
        with:
          check: ert
          file: "test/*-test.el"
